language: ruby
before_script:
  - rake setup
  - gem install rake -v "~> 0.9.2.2"
  - gem install minitest -v "~> 3.2"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - USE_RUBYGEMS="1.8.25"
  - USE_RUBYGEMS="2.0.3"
  - USE_RUBYGEMS="2.2.2"
matrix:
  exclude:
    - rvm: 2.0.0
      env: USE_RUBYGEMS="1.8.25"
