sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - 2.1.10
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rake test
  - bundle exec rake package
  - gem install --local pkg/gem-compiler-*.gem
deploy:
  - provider: rubygems
    api_key:
      secure: GzcHK3D4/hNbU9BcpxqOR03I0bPqVdz4flz8UYX5wo6MmnmCqpqCyRvXJfBE62V47QFB8UUeMCtCQ1xWVHqZAxHCWIq9LwpVOxBMwcNjviF0sEuDyUiySlQzj2x0AFd9h1uLqRNVBH0AKs1jwB4wtcJF4baJxo3oMZH+Doxi44I=
    gem: gem-compiler
    on:
      tags: true
      repo: luislavena/gem-compiler
      rvm: 2.1.10
  - provider: releases
    api_key:
      secure: XahX146zzKPJHx7KlsI3pFNC201wuw3Az6+3eP62NdV6MVqjuazZ0XQZjUlemMSHhnpdk1MC7llqkwrl3Xvk2+WvpMMgvfnUNRP/ND+bjGfX/O/VjnG6PAjshGEI6UT+QfeIxglMVvYX7u1e4NWH3BzIUixoHulx6kRffuq+yz0=
    file_glob: true
    file: "pkg/gem-compiler-*.gem"
    on:
      tags: true
      repo: luislavena/gem-compiler
      rvm: 2.1.10
